import os
import json
import subprocess
import sys

from fastapi import FastAPI, HTTPException, Depends, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from sqlalchemy import create_engine, Column, Integer, String, Text, Boolean, DateTime, ForeignKey
from sqlalchemy.orm import sessionmaker, Session, declarative_base
import datetime
from database import SessionLocal, ProjectModel, WorkflowStateModel, AgentArtifactModel, SystemWorkspaceModel
from agent_1_scoper import run_scoper_pipeline
from agent_2_hld import run_hld_pipeline
from agent_3_lld import run_lld_pipeline


class DashboardOverviewResponse(BaseModel):
    total_projects: int
    active_agent_loops: int
    compliance_violations_prevented: int
    system_latency_ms: float


class AgentTelemetryMetrics(BaseModel):
    agent_name: str
    phase: str
    tokens_consumed: int
    execution_status: str
    last_active: str


class GovernanceDecisionRequest(BaseModel):
    project_id: int
    action: str  # "approve" or "reject"
    feedback: str = ""

app = FastAPI(title="Volutrum Central Workflow Engine", version="1.0.5")

origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",    # 🚀 Add this
    "http://127.0.0.1:3001",    # 🚀 Add this
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,            # Allows your Next.js dev server access
    allow_credentials=True,
    allow_methods=["*"],              # Allows GET, POST, OPTIONS, etc.
    allow_headers=["*"],              # Allows all custom operational header types
)

# Dependency to get db session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

def get_or_create_workspace(db: Session) -> SystemWorkspaceModel:
    """Helper to ensure row 1 always exists as our standalone state tracking channel."""
    workspace = db.query(SystemWorkspaceModel).filter(SystemWorkspaceModel.id == 1).first()
    if not workspace:
        workspace = SystemWorkspaceModel(id=1, current_phase="scoping", status="idle")
        db.add(workspace)
        db.commit()
        db.refresh(workspace)
    return workspace

class InitializeRequest(BaseModel):
    idea: str


# --- PYDANTIC SCHEMAS ---
class ChatMessage(BaseModel):
    role: str
    content: str


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[ChatMessage]


class ProjectInitRequest(BaseModel):
    idea: str


class DecisionRequest(BaseModel):
    decision: str  # "approve" or "alter"
    feedback: str = ""


# --- REUSABLE ORCHESTRATION PIPELINE LOGIC ---
def trigger_agent_script(script_name: str, project_id: int, feedback: str = ""):
    """Safely executes localized agent execution binaries."""
    # Write environment context variables or execution arguments so the sub-agent knows what to read
    os.environ["VOLUTRUM_PROJECT_ID"] = str(project_id)
    os.environ["VOLUTRUM_FEEDBACK"] = feedback

    # Fire decoupled sub-agent processing script
    subprocess.run([sys.executable, script_name], check=True)


@app.get("/v1/models")
async def list_models():
    return {
        "object": "list",
        "data": [{"id": "volutrum-pipeline", "object": "model", "owned_by": "volutrum-core"}]
    }


@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest, db: Session = Depends(get_db)):
    global response_text
    user_message = request.messages[-1].content.strip()

    # 1. Fetch active session or spin up a greenfield workspace
    project = db.query(ProjectModel).order_by(ProjectModel.id.desc()).first()

    if not project or user_message.lower().startswith("new project:"):
        # Initialize a new greenfield project structure
        project_name = f"Project-{datetime.datetime.now().strftime('%Y%m%d%H%M')}"
        idea = user_message.replace("new project:",
                                    "").strip() if "new project:" in user_message.lower() else user_message

        project = ProjectModel(name=project_name, raw_idea=idea)
        db.add(project)
        db.commit()

        wf_state = WorkflowStateModel(project_id=project.id, current_phase="scoping", status="running")
        db.add(wf_state)
        db.commit()

        # Trigger Agent 1
        trigger_agent_script("agent_1_scoper.py", project.id)

        # Read artifact output generated by script
        with open("phase1_scope.md", "r", encoding="utf-8") as f:
            content = f.read()

        artifact = AgentArtifactModel(project_id=project.id, phase_name="scoping", artifact_content=content)
        db.add(artifact)
        db.commit()

        response_text = f"### 🤖 Volutrum Scoping Agent Complete\n\n{content}\n\n---\n👉 **Type 'approve' to push to Architecture Design (HLD), or type feedback to adjust scope:**"
        return create_openai_response(response_text)

    # 2. Process Stateful Hand-offs and Human Reviews
    wf = db.query(WorkflowStateModel).filter(WorkflowStateModel.project_id == project.id).first()

    if not wf:
        wf = WorkflowStateModel(project_id=project.id, current_phase="scoping", status="running")
        db.add(wf)
        db.commit()

    latest_artifact = db.query(AgentArtifactModel).filter(
        AgentArtifactModel.project_id == project.id,
        AgentArtifactModel.phase_name == wf.current_phase
    ).order_by(AgentArtifactModel.version.desc()).first()

    if not latest_artifact:
        latest_artifact = AgentArtifactModel(
            project_id=project.id,
            phase_name=wf.current_phase,
            artifact_content="",
            human_feedback="",
            version=1
        )
        db.add(latest_artifact)
        db.commit()

    if wf.current_phase == "scoping":
        if user_message.lower() == "approve":
            wf.current_phase = "hld"
            db.commit()

            trigger_agent_script("agent_2_hld.py", project.id)
            with open("phase2_hld.md", "r", encoding="utf-8") as f:
                content = f.read()

            new_art = AgentArtifactModel(project_id=project.id, phase_name="hld", artifact_content=content)
            db.add(new_art)
            db.commit()

            response_text = f"### 📐 Volutrum Architecture HLD Complete\n\n{content}\n\n---\n👉 **Type 'approve' to push to Low-Level Engineering, or type feedback to alter architecture:**"
        else:
            # Loop-back iteration execution
            latest_artifact.human_feedback = user_message
            latest_artifact.version += 1
            db.commit()

            trigger_agent_script("agent_1_scoper.py", project.id, feedback=user_message)
            with open("phase1_scope.md", "r", encoding="utf-8") as f:
                content = f.read()
            latest_artifact.artifact_content = content
            db.commit()
            response_text = f"🔄 **Scope Updated via Human Loop-back Input:**\n\n{content}"

    elif wf.current_phase == "hld":
        if user_message.lower() == "approve":
            wf.current_phase = "lld"
            db.commit()

            trigger_agent_script("agent_3_lld.py", project.id)
            with open("phase3_lld.md", "r", encoding="utf-8") as f:
                content = f.read()

            new_art = AgentArtifactModel(project_id=project.id, phase_name="lld", artifact_content=content)
            db.add(new_art)
            db.commit()
            response_text = f"### 💻 Volutrum Low-Level Technical Blueprint Complete\n\n{content}\n\n---\n🎉 **Greenfield Engineering Phase 1 Run Successfully Processed!**"
        else:
            latest_artifact.human_feedback = user_message
            latest_artifact.version += 1
            db.commit()

            trigger_agent_script("agent_2_hld.py", project.id, feedback=user_message)
            with open("phase2_hld.md", "r", encoding="utf-8") as f:
                content = f.read()
            latest_artifact.artifact_content = content
            db.commit()
            response_text = f"🔄 **HLD Architecture Refactored via Human Feedback Loop:**\n\n{content}"

    elif wf.current_phase == "lld":
        if user_message.lower() == "approve":
            wf.current_phase = "completed"
            db.commit()
            response_text = "🎉 **Volutrum Blueprint Run Finalized!** The architecture layout, compliance scopes, and AIBOM layouts have been successfully signed off and logged to the history matrix."
        else:
            latest_artifact.human_feedback = user_message
            latest_artifact.version += 1
            db.commit()

            trigger_agent_script("agent_3_lld.py", project.id, feedback=user_message)
            with open("phase3_lld.md", "r", encoding="utf-8") as f:
                content = f.read()
            latest_artifact.artifact_content = content
            db.commit()
            response_text = f"🔄 **LLD Engineering Layout Refactored via Feedback Loop:**\n\n{content}"

    else:
        response_text = ("ℹ️ **Volutrum Lifecycle Session Complete.** To spin up a brand new workspace layout from "
                         "scratch, simply type your next prompt starting with `new project: <your idea>`.")

    return create_openai_response(response_text)


@app.get("/api/dashboard/overview", response_model=DashboardOverviewResponse)
async def get_dashboard_overview(db: Session = Depends(get_db)):
    """Provides high-level aggregate data for the main executive console."""
    total_p = db.query(ProjectModel).count()
    active_loops = db.query(WorkflowStateModel).filter(WorkflowStateModel.status == "running").count()

    # Greenfield simulated metrics for security audit metrics (Phase 3 compliance link)
    compliance_blocks = 14  # Injected via local Presidio interceptor logs later
    avg_latency = 1420.5  # Milliseconds

    return {
        "total_projects": total_p,
        "active_agent_loops": active_loops,
        "compliance_violations_prevented": compliance_blocks,
        "system_latency_ms": avg_latency
    }


@app.get("/api/dashboard/agent-telemetry", response_model=List[AgentTelemetryMetrics])
async def get_agent_telemetry(db: Session = Depends(get_db)):
    """Provides real-time tracing across the matrix of the 9 specialized agents."""
    # Queries our workflow table to check which phase is currently holding execution tokens
    active_workflows = db.query(WorkflowStateModel).all()

    telemetry_board = []
    for wf in active_workflows:
        # Map our active states back to trace names
        phase_mapping = {
            "scoping": "Agent 1: Requirements Extractor",
            "hld": "Agent 2: Global Architect",
            "lld": "Agent 3: Low-Level Patch Engineer",
            "completed": "System Idle"
        }

        telemetry_board.append({
            "agent_name": phase_mapping.get(wf.current_phase, "Unknown Specialized Agent"),
            "phase": wf.current_phase,
            "tokens_consumed": 2405,  # Calculated token counter metric mapping
            "execution_status": wf.status,
            "last_active": datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        })

    # Default boilerplate fallback lines if the database is currently fresh/empty
    if not telemetry_board:
        return [{
            "agent_name": "Agent 1: Requirements Extractor",
            "phase": "scoping",
            "tokens_consumed": 0,
            "execution_status": "sleeping",
            "last_active": "N/A"
        }]

    return telemetry_board


@app.post("/api/workflow/decision")
async def handle_decision(payload: DecisionRequest, background_tasks: BackgroundTasks, db: Session = Depends(get_db)):
    workspace = get_or_create_workspace(db)

    if payload.decision == "approve":
        if workspace.current_phase == "scoping":
            workspace.current_phase = "hld"
            workspace.status = "running"
            workspace.hld_artifact = None
            db.commit()
            background_tasks.add_task(run_hld_pipeline, "")
        elif workspace.current_phase == "hld":
            workspace.current_phase = "lld"
            workspace.status = "running"
            workspace.lld_artifact = None
            db.commit()
            background_tasks.add_task(run_lld_pipeline, "")
        elif workspace.current_phase == "lld":
            workspace.current_phase = "completed"
            workspace.status = "done"
            db.commit()

    elif payload.decision == "alter":
        if workspace.current_phase == "scoping":
            workspace.status = "running"
            workspace.scoping_artifact = None
            db.commit()
            background_tasks.add_task(run_scoper_pipeline, workspace.raw_idea, payload.feedback)
        elif workspace.current_phase == "hld":
            workspace.status = "running"
            workspace.hld_artifact = None
            db.commit()
            background_tasks.add_task(run_hld_pipeline, payload.feedback)
        elif workspace.current_phase == "lld":
            workspace.status = "running"
            workspace.lld_artifact = None
            db.commit()
            background_tasks.add_task(run_lld_pipeline, payload.feedback)

    return {"status": "success"}


@app.get("/api/workflow/artifact")
async def get_current_state(db: Session = Depends(get_db)):
    """The frontend calls this on mount/refresh to restore the exact current pipeline state."""
    workspace = get_or_create_workspace(db)

    # Determine what content should be rendering based on the active phase
    content = "### ⏳ System Ready\nEnter your concept above to initialize the pipeline."
    if workspace.current_phase == "scoping":
        content = workspace.scoping_artifact or "### ⏳ Scoping Generation In Progress..."
    elif workspace.current_phase == "hld":
        content = workspace.hld_artifact or "### ⏳ HLD Generation In Progress..."
    elif workspace.current_phase == "lld":
        content = workspace.lld_artifact or "### ⏳ LLD Generation In Progress..."
    elif workspace.current_phase == "completed":
        content = "### 🎉 Blueprint Suite Finalized!\nAll requirements, HLD, and LLD layers successfully processed."

    return {
        "phase": workspace.current_phase,
        "status": workspace.status,
        "content": content,
        "idea": workspace.raw_idea
    }


@app.post("/api/workflow/initialize")
async def initialize_workspace(payload: InitializeRequest, background_tasks: BackgroundTasks,
                               db: Session = Depends(get_db)):
    """Wipes any old state and triggers Agent 1 on the single workspace footprint."""
    workspace = get_or_create_workspace(db)

    # Overwrite the singular workspace state
    workspace.raw_idea = payload.idea
    workspace.current_phase = "scoping"
    workspace.status = "running"
    workspace.scoping_artifact = None
    workspace.hld_artifact = None
    workspace.lld_artifact = None
    db.commit()

    print("🚀 [Core Engine] Workspace row 1 reset with new concept. Dispatching Agent 1...")
    background_tasks.add_task(run_scoper_pipeline, payload.idea, "")  # Direct background task handoff
    return {"status": "success"}


@app.post("/api/workflow/reset")
async def reset_workspace(db: Session = Depends(get_db)):
    """🚨 DELETION / RESTART ROUTE: Clean wipe back to terminal zero status."""
    workspace = get_or_create_workspace(db)
    workspace.raw_idea = None
    workspace.current_phase = "scoping"
    workspace.status = "idle"
    workspace.scoping_artifact = None
    workspace.hld_artifact = None
    workspace.lld_artifact = None
    db.commit()
    return {"status": "success"}


def create_openai_response(text: str):
    return {
        "id": "chatcmpl-volutrumcore",
        "object": "chat.completion",
        "model": "volutrum-pipeline",
        "choices": [{"index": 0, "message": {"role": "assistant", "content": text}, "finish_reason": "stop"}]
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=5000)