import os
import json
import subprocess
import sys

from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel
from typing import List, Optional
from sqlalchemy import create_engine, Column, Integer, String, Text, Boolean, DateTime, ForeignKey
from sqlalchemy.orm import sessionmaker, Session, declarative_base
import datetime

# --- CONFIGURATION & DATABASE INITIALIZATION ---
DATABASE_URL = "sqlite:///./volutrum_platform.db"  # Lightweight SQLite for greenfield prototyping
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

app = FastAPI(title="Volutrum Central Workflow Engine", version="1.0.0")


# --- SQLALCHEMY MODELS ---
class ProjectModel(Base):
    __tablename__ = "projects"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    raw_idea = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


class WorkflowStateModel(Base):
    __tablename__ = "workflow_state"
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="CASCADE"), primary_key=True)
    current_phase = Column(String, default="scoping")
    status = Column(String, default="pending_execution")


class AgentArtifactModel(Base):
    __tablename__ = "agent_artifacts"
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="CASCADE"))
    phase_name = Column(String, nullable=False)
    artifact_content = Column(Text)
    human_feedback = Column(Text, default="")
    is_approved = Column(Boolean, default=False)
    version = Column(Integer, default=1)


Base.metadata.create_all(bind=engine)


# Dependency to get db session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# --- PYDANTIC SCHEMAS ---
class ChatMessage(BaseModel):
    role: str
    content: str


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[ChatMessage]


# --- REUSABLE ORCHESTRATION PIPELINE LOGIC ---
def trigger_agent_script(script_name: str, project_id: int, feedback: str = ""):
    """Safely executes localized agent execution binaries."""
    # Write environment context variables or execution arguments so the sub-agent knows what to read
    os.environ["VOLUTRUM_PROJECT_ID"] = str(project_id)
    os.environ["VOLUTRUM_FEEDBACK"] = feedback

    # Fire decoupled sub-agent processing script
    subprocess.run([sys.executable, script_name], check=True)


# --- OPENAI-COMPATIBLE PLATFORM API ROUTES ---
@app.get("/v1/models")
async def list_models():
    return {
        "object": "list",
        "data": [{"id": "volutrum-pipeline", "object": "model", "owned_by": "volutrum-core"}]
    }


@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest, db: Session = Depends(get_db)):
    user_message = request.messages[-1].content.strip()

    # 1. Fetch active session or spin up a greenfield workspace
    project = db.query(ProjectModel).order_by(ProjectModel.id.desc()).first()

    if not project or user_message.lower().startswith("new project:"):
        # Initialize a new greenfield project structure
        project_name = f"Project-{datetime.datetime.now().strftime('%Y%m%d%H%M')}"
        idea = user_message.replace("new project:",
                                    "").strip() if "new project:" in user_message.lower() else user_message

        project = ProjectModel(name=project_name, raw_idea=idea)
        db.add(project)
        db.commit()

        wf_state = WorkflowStateModel(project_id=project.id, current_phase="scoping", status="running")
        db.add(wf_state)
        db.commit()

        # Trigger Agent 1
        trigger_agent_script("agent_1_scoper.py", project.id)

        # Read artifact output generated by script
        with open("phase1_scope.md", "r", encoding="utf-8") as f:
            content = f.read()

        artifact = AgentArtifactModel(project_id=project.id, phase_name="scoping", artifact_content=content)
        db.add(artifact)
        db.commit()

        response_text = f"### 🤖 Volutrum Scoping Agent Complete\n\n{content}\n\n---\n👉 **Type 'approve' to push to Architecture Design (HLD), or type feedback to adjust scope:**"
        return create_openai_response(response_text)

    # 2. Process Stateful Hand-offs and Human Reviews
    wf = db.query(WorkflowStateModel).filter(WorkflowStateModel.project_id == project.id).first()

    if not wf:
        wf = WorkflowStateModel(project_id=project.id, current_phase="scoping", status="running")
        db.add(wf)
        db.commit()

    latest_artifact = db.query(AgentArtifactModel).filter(
        AgentArtifactModel.project_id == project.id,
        AgentArtifactModel.phase_name == wf.current_phase
    ).order_by(AgentArtifactModel.version.desc()).first()

    if not latest_artifact:
        latest_artifact = AgentArtifactModel(
            project_id=project.id,
            phase_name=wf.current_phase,
            artifact_content="",
            human_feedback="",
            version=1
        )
        db.add(latest_artifact)
        db.commit()

    if wf.current_phase == "scoping":
        if user_message.lower() == "approve":
            wf.current_phase = "hld"
            db.commit()

            trigger_agent_script("agent_2_hld.py", project.id)
            with open("phase2_hld.md", "r", encoding="utf-8") as f:
                content = f.read()

            new_art = AgentArtifactModel(project_id=project.id, phase_name="hld", artifact_content=content)
            db.add(new_art)
            db.commit()

            response_text = f"### 📐 Volutrum Architecture HLD Complete\n\n{content}\n\n---\n👉 **Type 'approve' to push to Low-Level Engineering, or type feedback to alter architecture:**"
        else:
            # Loop-back iteration execution
            latest_artifact.human_feedback = user_message
            latest_artifact.version += 1
            db.commit()

            trigger_agent_script("agent_1_scoper.py", project.id, feedback=user_message)
            with open("phase1_scope.md", "r", encoding="utf-8") as f:
                content = f.read()
            latest_artifact.artifact_content = content
            db.commit()
            response_text = f"🔄 **Scope Updated via Human Loop-back Input:**\n\n{content}"

    elif wf.current_phase == "hld":
        if user_message.lower() == "approve":
            wf.current_phase = "lld"
            db.commit()

            trigger_agent_script("agent_3_lld.py", project.id)
            with open("phase3_lld.md", "r", encoding="utf-8") as f:
                content = f.read()

            new_art = AgentArtifactModel(project_id=project.id, phase_name="lld", artifact_content=content)
            db.add(new_art)
            db.commit()
            response_text = f"### 💻 Volutrum Low-Level Technical Blueprint Complete\n\n{content}\n\n---\n🎉 **Greenfield Engineering Phase 1 Run Successfully Processed!**"
        else:
            latest_artifact.human_feedback = user_message
            latest_artifact.version += 1
            db.commit()

            trigger_agent_script("agent_2_hld.py", project.id, feedback=user_message)
            with open("phase2_hld.md", "r", encoding="utf-8") as f:
                content = f.read()
            latest_artifact.artifact_content = content
            db.commit()
            response_text = f"🔄 **HLD Architecture Refactored via Human Feedback Loop:**\n\n{content}"

    return create_openai_response(response_text)


def create_openai_response(text: str):
    return {
        "id": "chatcmpl-volutrumcore",
        "object": "chat.completion",
        "model": "volutrum-pipeline",
        "choices": [{"index": 0, "message": {"role": "assistant", "content": text}, "finish_reason": "stop"}]
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=5000)